### ISSUE TITLE
Error _input_sources_get(self.get_source()) : TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by HugoDuret** [psmsmets/samsung_mdc#3]
I have this code to check whether the screen is in the "hdmi1"  mode: 
```
mdc = MultipleDisplayControl(ip, port, mdc_id)
mdc.connect()
is_mode_hdmi_on = mdc.source == 'hdmi1'
mdc.close()
```

It throws an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/samsung_mdc/mdc.py", line 443, in source
    _input_sources_get(self.get_source())
TypeError: 'dict' object is not callable
```

I believe it is because the _input_sources_get  object is defined as this:
```
_input_sources_get = {
    **_input_sources_set,
    0x1F: 'DVI_video',
    0x22: 'HDMI1_PC',
    0x24: 'HDMI2_PC',
}
```

I am not an expert in python so I don't know yet how to resolve this.
I'll look into it but any fix would be appreciated.

**Comment by vgavro** [comment]
If you're ok with asyncio, you may want to try this project:
https://github.com/vgavro/samsung-mdc
```python3
import asyncio
from samsung_mdc import MDC

async def main(ip, display_id):
    async with MDC(ip, verbose=True) as mdc:
        status = await mdc.status(display_id)
        is_mode_hdmi_on = status[3] in (
            MDC.input_source.INPUT_SOURCE_STATE.HDMI1,
            MDC.input_source.INPUT_SOURCE_STATE.HDMI2,
        )
asyncio.run(main('192.168.0.10', 1))
```
But note - some samsung models reporting HDMI1 input source when they are powered off, even if they will be in other modes on powering on.
